version: '2'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: docker_development
      MYSQL_ROOT_PASSWORD: fasjkdl29
      MYSQL_USER: hogehoge
      MYSQL_PASSWORD: fasjkdl29
    ports:
      - '3306:3306'
  web:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    depends_on:
      - db
    volumes:
      - "${PWD}:/var/www/html"
    ports:
      - '8000:8000'
